import {
  Scissors,
  Grip,
  Wrench,
  Hammer,
  Drill,
  Disc,
  Gauge,
  Zap,
  Radar,
  CircleGauge,
  Construction,
  HandMetal,
  Glasses,
  HardHat,
  Cable,
  Boxes,
  Component,
  Link2,
  Layers,
  Plug,
  ToggleLeft,
  SquareDashed,
  Lightbulb,
  ZapOff,
  ShieldCheck,
  CircuitBoard,
  Milestone,
  Package,
} from "lucide-react";

// Real product photos vary per admin/supplier and aren't something we can
// license or fabricate per catalog line — these are recognizable pictograms
// (not claimed to depict the exact product) so a standard-catalog row is
// visually identifiable at a glance before an admin uploads their own photo.
export const STANDARD_ICONS: Record<string, typeof Wrench> = {
  "Cleşte dezizolator": Scissors,
  "Cleşte patent": Grip,
  "Cleşte cu tăiş lateral": Scissors,
  "Cleşte de sertizat papuci": Grip,
  "Set şurubelniţe izolate VDE 1000V": Wrench,
  "Cheie reglabilă (cheie franceză)": Wrench,
  "Ciocan electrician": Hammer,
  "Cutter/cuţit universal": Scissors,
  "Fierăstrău manual pentru metal": Hammer,
  "Maşină de găurit cu percuţie": Drill,
  "Set burghie beton (diverse diametre)": Drill,
  "Șurubelniţă electrică/acumulator": Drill,
  "Disc de tăiere flex — metal/inox": Disc,
  "Multimetru digital": Gauge,
  "Tester ordine faze / nul-fază": Zap,
  "Creion fazometric": Zap,
  "Detector cabluri/metale sub tencuială": Radar,
  "Megohmetru (tester izolaţie)": CircleGauge,
  "Scară telescopică 3m": Construction,
  "Schelă mobilă mică": Construction,
  "Mănuşi electroizolante": HandMetal,
  "Ochelari de protecţie": Glasses,
  "Cască de protecţie": HardHat,
  "Cablu CYA 1.5mm²": Cable,
  "Cablu CYA 2.5mm²": Cable,
  "Cablu FY 1.5mm²": Cable,
  "Cablu MYYM 3x2.5": Cable,
  "Doză derivaţie": Boxes,
  "Tub riflat (copex) Ø16": Component,
  "Canal cablu PVC": Component,
  "Bridă (colier) cablu 2.5x100mm": Link2,
  "Clemă de legătură (tip Wago)": Link2,
  "Papuc terminal cablu (set diverse)": Link2,
  "Bandă izolatoare electrică": Layers,
  "Priză simplă cu împământare": Plug,
  "Întrerupător simplu, îngropat": ToggleLeft,
  "Întrerupător cap scară": ToggleLeft,
  "Ramă/capac pentru mecanism priză-întrerupător": SquareDashed,
  "Bec LED": Lightbulb,
  "Spot LED încastrat": Lightbulb,
  "Siguranţă automată (disjunctor)": ZapOff,
  "Siguranţă diferenţială (RCD)": ShieldCheck,
  "Tablou electric modular": CircuitBoard,
  "Electrod de împământare": Milestone,
  "Bandă/platbandă de împământare": Layers,
};

export function getMaterialIcon(name: string, kind: string) {
  return STANDARD_ICONS[name] ?? (kind === "tool" ? Wrench : Package);
}
